name: Create Release
run-name: ${{ github.actor }} is creating new release

on:
  workflow_dispatch:
    inputs:
      tagname:
        description: "tag name"

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tagname }}
          release_name: ${{ github.event.inputs.tagname }}
          draft: false
          prerelease: false
      - name: Create source distribution
        run: |
            set -x
            git clone --recursive https://github.com/oskarirauta/openwrt-banner.git openwrt-banner-${{ github.event.inputs.tagname }}
            # Cleanup
            find openwrt-banner-${{ github.event.inputs.tagname }} -name '.git*' -exec rm -rv {} \; || true
            tar -czf "openwrt-banner-${{ github.event.inputs.tagname }}.tar.gz" "openwrt-banner-${{ github.event.inputs.tagname }}"
      - name: Upload source distribution
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: ./openwrt-banner-${{ github.event.inputs.tagname }}.tar.gz
          asset_name: openwrt-banner-${{ github.event.inputs.tagname }}.tar.gz
          asset_content_type: application/tar.gz
