name: Create Release
run-name: ${{ github.actor }} is creating new release

on:
  workflow_dispatch:
    inputs:
      tagname:
        description: "tag name"
        default: "World"

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch "master"
        uses: actions/checkout@v2
        with:
          ref: 'master'
      - name: Create release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tagname }}
          release_name: ${{ github.event.inputs.tagname }}
          draft: false
          prerelease: false
      - name: Create source distribution
        run: |
            set -x
            git submodule update --init
            git rev-parse HEAD > revision.txt
            NAME="openwrt-banner-${{ github.event.inputs.tagname }}"
            mkdir "/tmp/$NAME"
            cp -r * "/tmp/$NAME"
            mv "/tmp/$NAME" .
            # Cleanup
            find "$NAME" -name '.git*' -exec rm -rv {} \; || true
            tar -czf "$NAME.tar.gz" "$NAME"
      - name: Upload source distribution
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: ./openwrt-banner-${{ github.event.inputs.tagname }}.tar.gz
          asset_name: openwrt-banner-${{ github.event.inputs.tagname }}.tar.gz
          asset_content_type: application/tar.gz
