name: Create Release
run-name: ${{ github.actor }} is creating new release

on:
  push:
    tags: 
    - 'v*'
    branches: [master]
  release:
    types: [published]

concurrency:
  group: ${{format('release-{0}:{1}', github.repository, github.ref)}}
  cancel-in-progress: true

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Extract tag name
        id: get_tag
        run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"
      - name: Set filenames
        id: filenames
        run: |
          echo "::set-output name=name::openwrt-banner${{steps.get_tag.outputs.tag}}.tar.gz"
      - name: Create source distribution
        run: |
            set -x
            git submodule update --init
            git rev-parse HEAD > revision.txt
            NAME="openwrt-banner-${{steps.get_tag.outputs.tag}}"
            mkdir "/tmp/$NAME"
            cp -r * "/tmp/$NAME"
            mv "/tmp/$NAME" .
            # Cleanup
            find "$NAME" -name '.git*' -exec rm -rv {} \; || true
            tar -czf openwrt-banner-${{${{steps.get_tag.outputs.tag}}.tar.gz "$NAME"
            tar -czf ${{steps.filenames.outputs.src}} "$NAME"
      - name: Get tag message
        run: |
          tagName=${{steps.get_tag.outputs.tag}}
          tagType=$(git cat-file -t $tagName)
          if [[ "$tagType" == "tag" ]]; then
            tagMsg="$(git tag -l --format='%(contents)' $tagName)"
            # Make sure to keep newlines and add an empty line before and after the message for better formatting
            echo "TAG_MSG<<EOF" >> $GITHUB_ENV
            echo "" >> $GITHUB_ENV
            echo "$tagMsg" >> $GITHUB_ENV
            echo "" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          else
            echo "TAG_MSG=" >> $GITHUB_ENV
          fi
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Return To The Roots (Settlers II(R) Clone)
            ${{ env.TAG_MSG }}
            - ${{steps.filenames.outputs.src}} contains all source files including the submodules
            - ${{steps.filenames.outputs.devTools}} contains optional binaries for development. Extract over the source folder if required
          draft: false
          prerelease: false
      - name: Upload source distribution
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{steps.filenames.outputs.src}}
          asset_name: ${{steps.filenames.outputs.src}}
          asset_content_type: application/tar.gz
